server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://party-games-database.cigcayr0ktuk.us-east-2.rds.amazonaws.com:3306/PartyGamesDatabase
    username: admin
    password: coffeeparty7