server:
  port: ${PORT:8080}
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://partyrgame.com:3306/partyrdb
    url: jdbc:mysql://127.0.0.1:3306/partyrdb
    # username: root
    username: partyr
    password: Partyr@2019
  output:
    ansi:
      enabled: always
security:
  oauth2:
    client:
      clientId: 1092985979122-rq2djvc09cnp8p4k86v498fi2f3d97lm.apps.googleusercontent.com
      clientSecret: LMC7wCoEXW_HmqczmhLIsbCJ
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
